name: RSS to OneNote Sync
on:
  schedule:
    - cron: '0 2,6,10,18 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run RSS to OneNote sync
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CI: 'true'
        run: |
          python rss_to_onenote.py
      - name: Commit cache files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add token_cache.bin processed_items.txt
          git commit -m "Update token cache and processed items" || echo "No changes to commit"
          git push
EOF