name: RSS to OneNote Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies and MSAL token
        id: cache-pip-token
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            token_cache.bin
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-token-v2
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-token-v2
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- 新增：安装 Xvfb ---
      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # --- 修改：使用 xvfb-run 运行 Python 脚本 ---
      - name: Run sync script
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CI: true
        run: xvfb-run python rss_to_onenote.py # 在 python 命令前添加 xvfb-run

      # --- 缓存保存步骤不变 ---