name: RSS to OneNote Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # 关键：拉全历史，便于后面 pull --rebase
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script to Sync RSS
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ONENOTE_SECTION_NAME: ${{ secrets.ONENOTE_SECTION_NAME }}
          CI: true
        run: python -u rss_to_onenote.py

      - name: Encrypt state files
        if: always()
        env:
          STATE_KEY: ${{ secrets.STATE_KEY }}
        run: |
          set -e
          if [ -f token_cache.bin ]; then
            openssl enc -aes-256-cbc -md sha256 -salt -pbkdf2 -pass pass:"$STATE_KEY" \
              -in token_cache.bin -out token_cache.bin.enc && rm -f token_cache.bin
          fi
          if [ -f processed_items.txt ]; then
            openssl enc -aes-256-cbc -md sha256 -salt -pbkdf2 -pass pass:"$STATE_KEY" \
              -in processed_items.txt -out processed_items.txt.enc && rm -f processed_items.txt
          fi

      - name: Commit and Push encrypted state files
        if: always()
        run: |
          set -e
          git config --global user.name  'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # 关键：确保与远端 main 同步，避免 “fetch first”
          git fetch origin main
          git checkout main
          git pull --rebase origin main

          # 仅当有变化时才提交
          git add token_cache.bin.enc processed_items.txt.enc 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No encrypted state changes."
            exit 0
          fi

          git commit -m "Update encrypted state files"
          git push origin HEAD:main
