name: RSS to OneNote Sync

on:
  workflow_dispatch: # 允许手动触发运行
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分运行（北京时间每小时整点）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 缓存 pip 依赖
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-pip-

      # 缓存 token_cache.bin 和 processed_items.txt
      - name: Cache MSAL token and processed items
        id: cache-token
        uses: actions/cache@v4
        with:
          path: |
            ./rss2onenote/token_cache.bin
            ./rss2onenote/processed_items.txt
          key: ${{ runner.os }}-token-${{ hashFiles('./rss2onenote/token_cache.bin', './rss2onenote/processed_items.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-token-

      - name: Debug cache restore
        run: |
          echo "Cache hit: ${{ steps.cache-token.outputs.cache-hit }}"
          echo "Checking for cached files in ./rss2onenote/:"
          ls -la ./rss2onenote/ || echo "rss2onenote directory not found."
          ls -la ./rss2onenote/token_cache.bin || echo "token_cache.bin not found after cache restore."
          ls -la ./rss2onenote/processed_items.txt || echo "processed_items.txt not found after cache restore."
          if [ -f ./rss2onenote/token_cache.bin ]; then echo "token_cache.bin is readable."; else echo "token_cache.bin is missing."; fi
          if [ -f ./rss2onenote/processed_items.txt ]; then echo "processed_items.txt is readable."; else echo "processed_items.txt is missing."; fi

      - name: Install dependencies and system packages
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb dbus-x11
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script with virtual display and DBus fix
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CI: true
          LIBGL_ALWAYS_SOFTWARE: 1
          NO_GPU: 1
          DBUS_SESSION_BUS_ADDRESS: "/dev/null"
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 3
          echo "Starting rss_to_onenote.py at $(date)"
          python ./rss2onenote/rss_to_onenote.py
          echo "Finished rss_to_onenote.py at $(date)"
          if [ -f ./rss2onenote/token_cache.bin ]; then echo "Token cache updated successfully."; else echo "Token cache not updated."; fi
          if [ -f ./rss2onenote/processed_items.txt ]; then echo "Processed items updated successfully."; else echo "Processed items not updated."; fi