name: RSS to OneNote Sync

on:
  workflow_dispatch: # 允许手动触发运行
  schedule:
    - cron: '0 * * * *'  # 每小时的第 0 分运行（北京时间每小时整点）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies and MSAL token
        id: cache-pip-token
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ./token_cache.bin
            ./processed_items.txt  # 去重文件缓存
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-token-v6
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-token-v6
            ${{ runner.os }}-pip-

      - name: Debug cache restore
        run: |
          echo "Cache hit: ${{ steps.cache-pip-token.outputs.cache-hit }}"
          echo "Checking for cached token file:"
          ls -la ./token_cache.bin || echo "token_cache.bin not found after cache restore."
          ls -la ./processed_items.txt || echo "processed_items.txt not found after cache restore."
          if [ -f ./token_cache.bin ]; then echo "token_cache.bin is readable."; else echo "token_cache.bin is missing."; fi

      - name: Install dependencies and system packages
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb dbus-x11
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script with virtual display and DBus fix
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CI: true
          LIBGL_ALWAYS_SOFTWARE: 1
          NO_GPU: 1
          DBUS_SESSION_BUS_ADDRESS: "/dev/null"
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 3
          echo "Starting rss_to_onenote.py at $(date)"
          python rss_to_onenote.py
          echo "Finished rss_to_onenote.py at $(date)"
          if [ -f ./token_cache.bin ]; then echo "Token cache updated successfully."; else echo "Token cache not updated."; fi
          if [ -f ./processed_items.txt ]; then echo "Processed items updated successfully."; else echo "Processed items not updated."; fi