name: RSS to OneNote Sync

on:
  schedule:
    - cron: '0 * * * *'   # 每小时
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行前：把上次运行后加密保存的 token_cache.enc 解密成 token_cache.bin
      - name: Decrypt token cache if present
        env:
          STATE_KEY: ${{ secrets.STATE_KEY }}
        shell: bash
        run: |
          if [ -f token_cache.enc ]; then
            echo "$STATE_KEY" | openssl enc -aes-256-cbc -d -pbkdf2 -in token_cache.enc -out token_cache.bin -pass stdin
            echo "Decrypted token_cache.enc -> token_cache.bin"
          else
            echo "No token_cache.enc to decrypt (first run)."
          fi

      - name: Run Python Script to Sync RSS
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ONENOTE_SECTION_NAME: ${{ secrets.ONENOTE_SECTION_NAME }}
          CI: true
        run: python -u rss_to_onenote.py

      # 运行后：把新的 token_cache.bin 再加密成 token_cache.enc，避免被 GitHub 安全扫描拦截
      - name: Encrypt token cache for commit
        if: always()
        env:
          STATE_KEY: ${{ secrets.STATE_KEY }}
        shell: bash
        run: |
          if [ -f token_cache.bin ]; then
            echo "$STATE_KEY" | openssl enc -aes-256-cbc -pbkdf2 -salt -in token_cache.bin -out token_cache.enc -pass stdin
            echo "Encrypted token_cache.bin -> token_cache.enc"
          else
            echo "No token_cache.bin to encrypt."
          fi

      - name: Commit and Push State Files
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # 只提交加密后的文件！
          git add token_cache.enc processed_items.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update state files (encrypted token_cache, processed_items)"
            git push
          fi
