name: RSS to OneNote Sync

on:
  schedule:
    # 每小时运行一次 (在每小时的第0分钟)
    - cron: '0 * * * *'
  workflow_dispatch: # 允许从 Actions 页面手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # #################################################
      # 关键修改：在这里添加了 -u 参数
      # #################################################
      - name: Run Python Script to Sync RSS
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CI: true # 告诉脚本这是在自动化环境中运行
        run: python -u rss_to_onenote.py

      - name: Commit and Push State Files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add token_cache.bin processed_items.txt || echo "No state files to add."
          
          if git diff-index --quiet HEAD; then
            echo "No changes in state files to commit."
          else
            git commit -m "Update state files (token_cache, processed_items)"
            git push
          fi
